# Generated by Django 5.0.6 on 2024-06-08 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240102_2007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Daycome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('win', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_supplier_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wallet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payments', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lose_type', models.CharField(blank=True, max_length=100, null=True)),
                ('lose_money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='place',
        ),
        migrations.AddField(
            model_name='supplier',
            name='for_him',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('prand', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.kind')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('paid_money', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('method', models.CharField(choices=[('محفظة', 'محفظة'), ('نقدية', 'نقدية')], default='نقدية', max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.client')),
            ],
        ),
        migrations.CreateModel(
            name='RecentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, max_length=100, null=True)),
                ('action_sort', models.CharField(blank=True, max_length=100, null=True)),
                ('model_affected', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('crash', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='مباع', max_length=100, null=True)),
                ('method', models.CharField(choices=[('محفظة', 'محفظة'), ('نقدية', 'نقدية')], default='نقدية', max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sale_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.item')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('crash', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='مباع', max_length=100, null=True)),
                ('method', models.CharField(choices=[('محفظة', 'محفظة'), ('نقدية', 'نقدية')], default='نقدية', max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sale_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.item')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.supplier')),
            ],
        ),
    ]
