# Generated by Django 3.2.23 on 2024-07-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_loan_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='worker',
            new_name='employee',
        ),
    ]
