# Generated by Django 3.2.23 on 2024-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
